name: python-lint-and-test
on: [pull_request]
env:
  PYTHON_VERSION: 3.9
defaults:
  run:
    # Pythonのルートディレクトリを指定
    working-directory: ./pythonbase
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: make lint |& tee lint.log
        continue-on-error: true
      - name: Test
        run: make test |& tee test.log
        continue-on-error: true
      - name: Typecheck
        run: |
          echo 'typecheck<<EOF' >> $GITHUB_ENV
          { make typecheck |& tee typecheck.log; } && { echo 'Typecheck passed' >> $GITHUB_ENV ; } || { echo 'Typecheck failed' >> $GITHUB_ENV ; }
          cat typecheck.log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        continue-on-error: true
      - name: Comment PullRequest
        uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: 'Preview ${{ steps.deploy-to-webapp.outputs.webapp-url }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
