name: python-lint-and-test
on: [pull_request]
env:
  PYTHON_VERSION: 3.9
defaults:
  run:
    # Pythonのルートディレクトリを指定
    working-directory: ./pythonbase
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Lint
        run: make lint
      - name: Test
        if: always()
        run: make test
      - name: Typecheck
        if: always()
        run: make typecheck | reviewdog -f=mypy -name="mypy" -reporter=github-pr-review
