name: python-lint-and-test
on: [pull_request]
env:
  PYTHON_VERSION: 3.9
defaults:
  run:
    # Pythonのルートディレクトリを指定
    working-directory: ./pythonbase
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: make test
  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Typecheck
        run: make typecheck
