name: python-lint-and-test
on: [pull_request]
env:
  PYTHON_VERSION: 3.9
defaults:
  run:
    # Pythonのルートディレクトリを指定
    working-directory: ./pythonbase
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        id: lint
        run: make lint |& tee -a lint.log
        continue-on-error: true
      - name: Test
        id: test
        run: make test |& tee -a test.log
        continue-on-error: true
      - name: Typecheck
        id: typecheck
        run: make typecheck |& tee -a typecheck.log
        continue-on-error: true
      - name: Comment to pull request if lint or test failed
        uses: actions/github-script@v5
        if: steps.lint.outcome == 'failure' || steps.test.outcome == 'failure' || steps.typecheck.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const lintLog = fs.readFileSync('lint.log', 'utf8');
            const testLog = fs.readFileSync('test.log', 'utf8');
            const typecheckLog = fs.readFileSync('typecheck.log', 'utf8');
            const message = `
            ## Lint
            \`\`\`
            ${lintLog}
            \`\`\`
            ## Test
            \`\`\`
            ${testLog}
            \`\`\`
            ## Typecheck
            \`\`\`
            ${typecheckLog}
            \`\`\`
            `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });