name: python-lint-and-test
on: [pull_request]
env:
  PYTHON_VERSION: 3.9
defaults:
  run:
    # Pythonのルートディレクトリを指定
    working-directory: ./pythonbase
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys:  ${{ runner.os }}-pip-
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Lint
        run: make lint
      - name: Test
        if: always()
        run: make test
      - name: Typecheck
        if: always()
        run: make typecheck
